/**
 * mcd-email.ts — shared email-sending logic for MCD reports
 * Used by:
 *   • src/app/api/mcd/email/route.ts  (manual "Send Email" button)
 *   • src/lib/scheduler.ts             (auto-send after cron / Run Now)
 */

import { getDb, markMcdReportEmailed } from '@/lib/db'
import type { McdReport } from '@/lib/db'

// ── Helpers ───────────────────────────────────────────────────────────────

export function fmtReportDate(s: string) {
  try {
    return new Date(s + 'T12:00:00').toLocaleDateString('en-US', {
      weekday: 'short', month: 'short', day: 'numeric', year: 'numeric',
    })
  } catch { return s }
}

function esc(s: string) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

function inlineFmt(line: string): string {
  return esc(line)
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/`([^`]+)`/g, '<code style="background:#f3f4f6;padding:1px 5px;border-radius:3px;font-size:12px;font-family:monospace">$1</code>')
}

// ── HTML formatter ────────────────────────────────────────────────────────

export function buildMcdEmailHtml(report: McdReport): string {
  const typeLabel  = report.report_type.charAt(0).toUpperCase() + report.report_type.slice(1)
  const dateRange  = `${fmtReportDate(report.period_start)} – ${fmtReportDate(report.period_end)}`
  const subject    = `PHR MCD ${typeLabel} Report | ${dateRange}`
  const bodyHtml   = reportTextToHtml(report.content)

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(subject)}</title>
</head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">
<table width="100%" cellpadding="0" cellspacing="0" role="presentation">
<tr><td align="center" style="padding:24px 16px">
  <table width="100%" style="max-width:680px" cellpadding="0" cellspacing="0" role="presentation">

    <!-- Header -->
    <tr><td style="background:#1e2433;border-radius:12px 12px 0 0;padding:28px 32px">
      <table width="100%" cellpadding="0" cellspacing="0" role="presentation">
        <tr>
          <td>
            <div style="font-size:22px;margin-bottom:4px">📊</div>
            <h1 style="margin:0;color:#ffffff;font-size:20px;font-weight:700">PHR MCD ${esc(typeLabel)} Report</h1>
            <p style="margin:4px 0 0;color:rgba(255,255,255,0.55);font-size:13px">${esc(dateRange)} &nbsp;·&nbsp; Generated by PHR OS</p>
          </td>
          <td align="right" style="vertical-align:top">
            <div style="background:rgba(99,102,241,0.25);border:1px solid rgba(99,102,241,0.4);border-radius:6px;padding:4px 12px;display:inline-block">
              <span style="color:#a5b4fc;font-size:11px;font-weight:700;text-transform:uppercase">${esc(report.report_type)}</span>
            </div>
          </td>
        </tr>
      </table>
    </td></tr>

    <!-- Body -->
    <tr><td style="background:#ffffff;padding:28px 32px">
      ${bodyHtml}
    </td></tr>

    <!-- Footer -->
    <tr><td style="background:#f9fafb;border-radius:0 0 12px 12px;border-top:1px solid #e5e7eb;padding:16px 32px">
      <table width="100%" cellpadding="0" cellspacing="0" role="presentation">
        <tr>
          <td style="font-size:11px;color:#9ca3af">
            PHR OS &nbsp;·&nbsp; Marketing &amp; Conversions Director &nbsp;·&nbsp; Auto-generated report
          </td>
          <td align="right" style="font-size:11px;color:#9ca3af">
            Report #${report.id} &nbsp;·&nbsp; ${new Date(report.created_at).toLocaleString('en-US', { timeZone: 'America/Phoenix' })} MST
          </td>
        </tr>
      </table>
    </td></tr>

  </table>
</td></tr>
</table>
</body>
</html>`
}

function reportTextToHtml(text: string): string {
  const lines = text.split('\n')
  let html = ''

  for (const raw of lines) {
    const line = raw.trimEnd()
    if (!line.trim()) { html += '<div style="height:6px"></div>\n'; continue }

    if (/^\d+\)\s/.test(line)) {
      const num   = line.match(/^(\d+)/)?.[1] || ''
      const title = inlineFmt(line.replace(/^\d+\)\s+/, ''))
      html += `<div style="display:flex;align-items:center;gap:10px;margin:28px 0 10px">
        <div style="width:26px;height:26px;border-radius:50%;background:#4338ca;color:white;font-size:12px;font-weight:700;display:flex;align-items:center;justify-content:center;flex-shrink:0">${num}</div>
        <h2 style="margin:0;font-size:16px;font-weight:700;color:#1e2433;border-bottom:2px solid #e5e7eb;padding-bottom:8px;flex:1">${title}</h2>
      </div>\n`
      continue
    }
    if (line.startsWith('# '))   { html += `<h1 style="margin:8px 0 12px;font-size:18px;font-weight:700;color:#1e2433">${inlineFmt(line.slice(2))}</h1>\n`; continue }
    if (line.startsWith('## '))  { html += `<h2 style="margin:20px 0 8px;font-size:15px;font-weight:700;color:#1e2433;border-bottom:1px solid #e5e7eb;padding-bottom:6px">${inlineFmt(line.slice(3))}</h2>\n`; continue }
    if (line.startsWith('### ')) { html += `<h3 style="margin:14px 0 6px;font-size:13px;font-weight:600;color:#374151">${inlineFmt(line.slice(4))}</h3>\n`; continue }

    if (/^[•\-\*]\s/.test(line) || /^\s+[•\-\*]\s/.test(line)) {
      const indent  = line.match(/^(\s*)/)?.[1].length || 0
      const content = inlineFmt(line.replace(/^\s*[•\-\*]\s+/, ''))
      html += `<div style="display:flex;gap:8px;margin:3px 0;padding-left:${indent * 4}px"><span style="color:#6366f1;flex-shrink:0;margin-top:1px">•</span><span style="color:#374151;font-size:13px;line-height:1.7">${content}</span></div>\n`
      continue
    }
    if (/^\s*\d+\.\s/.test(line) && !/^\d+\)\s/.test(line)) {
      const num     = line.match(/^\s*(\d+)\./)?.[1] || ''
      const content = inlineFmt(line.replace(/^\s*\d+\.\s+/, ''))
      html += `<div style="display:flex;gap:8px;margin:3px 0;padding-left:8px"><span style="color:#6366f1;font-weight:600;flex-shrink:0;min-width:20px;font-size:13px">${num}.</span><span style="color:#374151;font-size:13px;line-height:1.7">${content}</span></div>\n`
      continue
    }
    if (line.includes('Confidence:') && line.includes('%')) {
      html += `<div style="background:#f0f4ff;border-left:3px solid #6366f1;padding:8px 12px;margin:10px 0;border-radius:0 6px 6px 0;font-size:12px;color:#374151">${inlineFmt(line)}</div>\n`
      continue
    }
    html += `<p style="margin:4px 0;font-size:13px;color:#374151;line-height:1.75">${inlineFmt(line)}</p>\n`
  }
  return html
}

// ── Main send function (used by route + scheduler) ────────────────────────

export interface SendMcdEmailResult {
  ok: boolean
  message?: string
  subject?: string
  error?: string
}

export async function sendMcdEmail(reportId: number): Promise<SendMcdEmailResult> {
  const webhook = process.env.MCD_N8N_EMAIL_WEBHOOK
  if (!webhook) return { ok: false, error: 'MCD_N8N_EMAIL_WEBHOOK not configured' }

  const report = getDb().prepare('SELECT * FROM mcd_reports WHERE id=?').get(reportId) as McdReport | undefined
  if (!report) return { ok: false, error: `Report #${reportId} not found` }

  const typeLabel = report.report_type.charAt(0).toUpperCase() + report.report_type.slice(1)
  const dateRange = `${fmtReportDate(report.period_start)} – ${fmtReportDate(report.period_end)}`
  const subject   = `PHR MCD ${typeLabel} Report | ${dateRange}`
  const html      = buildMcdEmailHtml(report)

  const payload = {
    subject,
    html,
    text:         report.content,
    report_type:  report.report_type,
    period_start: report.period_start,
    period_end:   report.period_end,
    report_id:    report.id,
  }

  const res = await fetch(webhook, {
    method:  'POST',
    headers: { 'Content-Type': 'application/json' },
    body:    JSON.stringify(payload),
    signal:  AbortSignal.timeout(30_000),
  })

  if (!res.ok) {
    const detail = await res.text().catch(() => '')
    return { ok: false, error: `N8N webhook returned ${res.status}: ${detail.slice(0, 300)}` }
  }

  markMcdReportEmailed(report.id)
  return { ok: true, message: `Report #${report.id} sent via email`, subject }
}
